package memory

import (
	"context"
	"fmt"
	"log/slog"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgxpool"

	"CapyClaw/internal/pond/ripple"
)

// SemanticStore manages semantic (knowledge) memories.
// Uses pure vector similarity search via pgvector + bge-m3 embeddings.
type SemanticStore struct {
	pool     *pgxpool.Pool
	search   *ripple.SearchEngine
	embedder EmbeddingGeneratorFunc
}

// NewSemanticStore creates a new semantic memory store.
func NewSemanticStore(pool *pgxpool.Pool, search *ripple.SearchEngine, embedder EmbeddingGeneratorFunc) *SemanticStore {
	return &SemanticStore{
		pool:     pool,
		search:   search,
		embedder: embedder,
	}
}

// SearchByVector retrieves semantic memories using a pre-computed embedding.
func (s *SemanticStore) SearchByVector(ctx context.Context, agentID uuid.UUID, embedding []float32, limit int) ([]MemoryEntry, error) {
	if s.pool == nil {
		return nil, nil
	}

	var results []MemoryEntry

	if s.search != nil {
		slog.Debug("semantic search: vector query")
		searchResults, err := s.search.Search(ctx, ripple.SearchQuery{
			AgentID:    agentID,
			Embedding:  embedding,
			MemoryType: "semantic",
			Limit:      limit,
		})
		if err != nil {
			return nil, fmt.Errorf("semantic vector search: %w", err)
		}

		for _, r := range searchResults {
			results = append(results, MemoryEntry{
				ID:              r.ID,
				AgentID:         agentID,
				MemoryType:      "semantic",
				Content:         r.Content,
				ImportanceScore: r.ImportanceScore,
			})
		}
	}

	// Increment access count for matched memories
	if len(results) > 0 {
		ids := make([]uuid.UUID, len(results))
		for i, r := range results {
			ids[i] = r.ID
		}
		_, _ = s.pool.Exec(ctx, `
			UPDATE memories
			SET access_count = COALESCE(access_count, 0) + 1, last_accessed_at = NOW()
			WHERE id = ANY($1)
		`, ids)
	}

	return results, nil
}

// Store saves a new semantic memory (embedding is generated by the extractor).
func (s *SemanticStore) Store(ctx context.Context, entry *MemoryEntry) error {
	if s.pool == nil {
		return fmt.Errorf("semantic store not initialized")
	}

	var memoryID uuid.UUID
	err := s.pool.QueryRow(ctx, `
		INSERT INTO memories (agent_id, tenant_id, memory_type, content, importance_score, source_session_id)
		VALUES ($1, $2, 'semantic', $3, $4, $5)
		RETURNING id
	`, entry.AgentID, entry.TenantID, entry.Content, entry.ImportanceScore, entry.SourceSessionID).Scan(&memoryID)
	if err != nil {
		return fmt.Errorf("storing semantic memory: %w", err)
	}

	entry.ID = memoryID
	return nil
}
